# -*- coding: utf-8 -*-
"""Detection_image_vedio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHLJKRMeEOzLz5e3mlP_ngjMdqosMwp6
"""

# Install YOLOv8
!pip install ultralytics roboflow

import ultralytics
ultralytics.checks()

!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="fu47PieMNjRBfh5WDiZT")
project = rf.workspace("roushan-kumar-jfa3j").project("ppe_automate")
version = project.version(1)
dataset = version.download("yolov11")

dataset.location

!yolo task=detect model=train data={dataset.location}/data.yaml model="yolo11n.pt" epochs=50 imgsz=650

from ultralytics import YOLO
from IPython.display import display, Image

Image("/content/runs/detect/train/confusion_matrix.png",width=600)

Image("/content/runs/detect/train/labels.jpg",width=600)

Image("/content/runs/detect/train/results.png",width=600)

Image("/content/runs/detect/train/train_batch0.jpg",width=600)

Image("/content/runs/detect/train/train_batch1.jpg",width=600)

!yolo task=detect mode=val model="/content/runs/detect/train/weights/best.pt" data={dataset.location}/data.yaml

!yolo task=detect mode=predict model="/content/runs/detect/train/weights/best.pt" conf=0.25 source=image_2.jpg save=True

#Image Detection

Image("/content/runs/detect/predict2/image_2.jpg",width=600)

#Vedio Detection

!yolo task=detect mode=predict model="/content/runs/detect/train/weights/best.pt" conf=0.25 source="/content/Vedio_01.mp4" save=True